FROM node:16-alpine AS dependencies
RUN apk add --no-cache libc6-compat

# Install Python
RUN apk add --update python3 make g++\
   && rm -rf /var/cache/apk/*
   
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

COPY ./ ./


CMD ["npm", "run", "start-dev"]