apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - decision-loop-client.yaml
images:
  - name: client-prod-image
    newName: 848184835076.dkr.ecr.us-east-1.amazonaws.com/client-prod
    newTag: latest
