FROM node:alpine
WORKDIR /app
COPY package.json ./
# Install Python
RUN apk add --update python3 make g++\
   && rm -rf /var/cache/apk/*
RUN npm install --legacy-peer-deps
COPY ./ ./

# Run in production mode
CMD ["npm", "start"]
