apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - decision-loop-server.yaml
images:
  - name: server-stage-image
    newName: 186647464304.dkr.ecr.eu-west-2.amazonaws.com/server-stage
    newTag: latest